<!DOCTYPE html>
<html lang="hi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>मेरा पहला GitHub पेज</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            text-align: center;
            padding-top: 50px;
        }
        h1 {
            color: #333;
        }
    </style>
</head>
<body>
    <h1>नमस्ते, दुनिया!</h1>
    <p>यह मेरा पहला GitHub Pages पर होस्ट किया गया वेबपेज है।</p>
</body>
</html>
